// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfxMyk0S7KfE9SXPzqI_RhT0V3KI7IdPA',
    appId: '1:788655675757:ios:ccd98279ddb278e703a264',
    messagingSenderId: '788655675757',
    projectId: 'shoesly-6fb72',
    storageBucket: 'shoesly-6fb72.appspot.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9LXsXcrBargt_m5AyVLVJfmc8VLH00Mw',
    appId: '1:788655675757:android:3b4ecd2e3b22415e03a264',
    messagingSenderId: '788655675757',
    projectId: 'shoesly-6fb72',
    storageBucket: 'shoesly-6fb72.appspot.com',
  );
}
